### ISSUE TITLE
Identify a more practical deviceID

### ISSUE THREAD

**Issue by akirk** [Automattic/chatrix#59] opened 2022-09-07 11:17 UTC
Using the same deviceID within chatrix logins to automatically invalidate old tokens upon login.

We don't want valid access tokens to remain in local storage.

Idea: use the browser user agent.

**Comment by psrpinto** [comment] 2023-01-11 15:23
Device ID is now randomly generated by hydrogen. As for invalidating access tokens, I think this would be a duplicate of #118. Closing.

**Closed by psrpinto** 2023-01-11 15:23 UTC
