### ISSUE TITLE
Notify user when chat messages are not accepted by the server

### ISSUE THREAD

**Issue by ashfame** [Automattic/chatrix#46] opened 2022-08-24 07:50 UTC
Handle 401 requests in Chatrix (when session is deleted from localstorage) and update state as logged out.

**Comment by psrpinto** [comment] 2023-01-11 15:14
Marking as duplicate of https://github.com/Automattic/chatrix/issues/118 and closing.

**Closed by psrpinto** 2023-01-11 15:14 UTC
Labels: bug

**Comment by psrpinto** [comment] 2023-01-11 15:48
Hydrogen already handles that case, I just tested your story above, and this is the result (without refreshing the page chatrix is in):

<img width="675" alt="Screenshot 2023-01-11 at 15 46 50" src="https://user-images.githubusercontent.com/550401/211851285-2ab1a981-a6c9-4886-aa67-2bdb793d4a07.png">

**Comment by ashfame** [comment] 2023-01-11 15:51
Cool!
